In [20]:
import numpy as np

def build_confusion_matrix(truth_vector, prediction_vector):
    classes = np.unique(np.intersect1d(truth_vector, prediction_vector))
    size = len(classes)
    matrix = np.zeros((size, size))
    for actual_class, predicated_class in zip(truth_vector, prediction_vector):
        matrix[actual_class, predicated_class] += 1
    return matrix

print("Expected output: \n{}".format(np.matrix([[1, 1, 0], [0, 1, 0], [0, 0, 1]])))
cm = build_confusion_matrix([0, 0, 1, 2], [1, 0, 1, 2])
print("Actual output: \n{}".format(cm))

Expected output: 
[[1 1 0]
 [0 1 0]
 [0 0 1]]
Actual output: 
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
