In [5]:
import numpy as np
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score  
#Load the input data
iris = datasets.load_iris()
#Taking first two features as follows −
#Load the input data
iris = datasets.load_iris()
#Taking first two features as follows −
X = iris.data[:, :2]
y = iris.target


In [6]:

x_train, x_test, y_train, y_test = train_test_split(X, iris.target, test_size=0.30, random_state=4)

# Making the SVM Classifer
Classifier = SVC(kernel="linear")

# Training the model on the training data and labels
Classifier.fit(x_train, y_train)

# Using the model to predict the labels of the test data
y_pred = Classifier.predict(x_test)

# Evaluating the accuracy of the model using the sklearn functions
accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)

# Printing the results
print("Accuracy for SVM is:",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy for SVM is: 84.44444444444444
Confusion Matrix
[[20  1  0]
 [ 0  8  2]
 [ 0  4 10]]
